[package]
name = "rust-guessing-game"
version = "0.1.0"
authors = ["Nico Bachner <yo@nicob.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.0"
